# -*- coding: utf-8 -*-
# !/usr/bin/env python -W ignore::DeprecationWarning
"""Physiological data conversion to BIDS"""

import gc
import os
import json
import click
import logging
import pandas as pd
from phys2bids.phys2bids import phys2bids
import glob

import sys

sys.path.append("../utils")


@click.command()
@click.argument("root", type=click.Path(exists=True))
@click.argument("save", type=click.Path())
@click.argument("sub", type=str)
@click.option("--ses", type=str, default=None, required=False)
@click.option("--tr", type=float, default=None, required=False)
@click.option("--ch_name", default=None, required=False)
def call_convert(root, save, sub, ses=None, tr=None, ch_name=None):
    """
    Call `convert` function only if `convert.py` is called as CLI

    For parameters description, please refer to the documentation of the `convert` function
    """
    if ch_name is not None:
        ch_name = json.loads(ch_name)
    convert(root, save, sub, ses, tr, ch_name)


def convert(root, save, sub, ses=None, tr=None, ch_name=None, overwrite=False):
    """
    Phys2Bids conversion for one subject data

    Parameters
    ----------
    root : str
        Root directory containing the `./utils/get_info.py` output. Example: "/home/user/dataset/info".
    save : str
        Directory to save the converted data. Example: "/home/user/dataset/converted/".
    subject : str
        Name of path for a specific subject. Example: "sub-01".
    sessions : list
        Name of path for specific session(s). Example: "ses-01" or ["ses-001", "ses-002"].
        Default to None.
    tr : float
        TR value used for the mri acquisition. If not specified, the function
        will find the value in the json file generated by `./utils/get_info.py`.
        Default to None.
    ch_name : list
        Name of the channels in the acqknowledge file. If not specified, the function
        will find the value in the json file generated by `./utils/get_info.py`.
        Default to None.

    See also
    --------
    https://phys2bids.readthedocs.io/en/latest/index.html

    Examples
    --------
    In script
    >>> convert(root="/home/user/dataset/info", save="/home/user/dataset/converted/", sub="sub-01", ses="ses-001", tr=1.49, ch_name=["EDA", "ECG", "TTL"])
    In terminal
    >>> python convert.py /home/user/dataset/info /home/user/dataset/converted/ sub-01 --ses ses-001 --tr 1.49 --ch_name '["EDA", "ECG", "TTL"]'
    NOTE: if you want to specify the `ch_name` using the CLI, specify your list inside single quote ('') just like the example above.
    """
    logger = logging.getLogger(__name__)
    # fetch info
    fetcher = f"{sub}_volumes_all-ses-runs.json"
    logger.info(f"Reading fetcher:\n{os.path.join(root, sub, fetcher)}")
    info = pd.read_json(os.path.join(root, sub, f"{sub}_volumes_all-ses-runs.json"))
    # define sessions
    if sessions is None:
        sessions = sorted(list(info.columns))
        # Remove the sessions that are already processed
        if overwrite is False:
            existing = [str(d[-8:-1]) for d in glob.glob(f"{root}{sub}/*/")]
            setA = set(sessions)
            # Get new set with elements that are only in sessions but not in existing
            sessions = sorted(list(setA.difference(existing)))

    elif isinstance(ses, list) is False:
        ses = [ses]
    # Define ch_name and trigger idx
    if info[ses]["ch_name"] is None:
        logger.info(
            "Warning: you did not specify a value for ch_name, the values that will be use are the following: "
        )
        ch_name = ["EDA", "PPG", "ECG", "TTL", "RSP"]
        info[ses]["ch_name"] = ch_name
        logger.info("Please make sure, those values are the right ones :\n{ch_name}")
        chtrig = 4
    else:
        # Define chtrig ; should find a way to find it from a list of possible values
        info[col].update({"ch_names": ["EDA", "PPG", "ECG", "TTL", "RSP"]})
        chtrig = info[ses]["ch_name"].index("TTL")

    # iterate through info
    for col in ses:
        # skip empty sessions
        if info[col] is None:
            continue
        logger.info(col)

        # Iterate through files in each session and run phys2bids
        filename = info[col]["in_file"]
        if filename is list:
            for i in range(len(filename) - 1):
                phys2bids(
                    filename[i],
                    info=False,
                    indir=os.path.join(root, sub, col),
                    outdir=os.path.join(save, sub, col),
                    heur_file=None,
                    sub=sub[-2:],
                    ses=col[-3:],
                    chtrig=chtrig,
                    chsel=None,
                    num_timepoints_expected=info[col]["recorded_triggers"][
                        f"run-0{i+1}"
                    ],
                    tr=info[col]["tr"],
                    thr=4,
                    pad=9,
                    ch_name=info[col]["ch_name"],
                    yml="",
                    debug=False,
                    quiet=False,
                )
        else:
            try:
                phys2bids(
                    filename,
                    info=False,
                    indir=os.path.join(root, "physio", sub, col),
                    outdir=os.path.join(save, sub, col),
                    heur_file=None,
                    sub=sub[-2:],
                    ses=col[-3:],
                    chtrig=chtrig,
                    chsel=None,
                    num_timepoints_expected=info[col]["recorded_triggers"]["run-01"],
                    tr=info[col]["tr"],
                    thr=4,
                    pad=9,
                    ch_name=info[col]["ch_name"],
                    yml="",
                    debug=False,
                    quiet=False,
                )
            except AttributeError:
                filename.sort()
                for i in range(len(filename)):
                    print(i)
                    phys2bids(
                        filename[i],
                        info=False,
                        indir=os.path.join(root, sub, col),
                        outdir=os.path.join(save, sub, col),
                        heur_file=None,
                        sub=sub[-2:],
                        ses=col[-3:],
                        chtrig=chtrig,
                        chsel=None,
                        num_timepoints_expected=info[col]["recorded_triggers"][
                            f"run-0{i+1}"
                        ],
                        tr=info[col]["tr"],
                        thr=4,
                        pad=9,
                        ch_name=info[col]["ch_name"],
                        yml="",
                        debug=False,
                        quiet=False,
                    )

            except TypeError:
                print(f"No input file for {col}")
                continue
        gc.collect()
        print("~" * 30)


if __name__ == "__main__":
    log_fmt = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    logging.basicConfig(level=logging.INFO, format=log_fmt)
    call_convert()
